### ISSUE TITLE
failed_to_acquire_token_silently in TodoController.cs

### ISSUE THREAD

**Issue by chrisgundersen** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#15]
We've tried to set up this project a few times to run the sample but we consistently get a `failed_to_acquire_token_silently` exception on line  34 of `TodoController.cs`. There are times this request will work the first time, but subsequent requests always fail and end up being redirected to an `AccessDenied` action in the `Account` controller which doesn't exist, resulting in a 404.

Any ideas what might be going on?

**Comment by mgmiles** [comment]
I am seeing the same issue. Any ideas?

**Comment by michael-freidgeim-webjet** [comment]
I beleive the issue is described in http://stackoverflow.com/questions/41519132/how-to-store-the-token-received-in-acquiretokenasync-with-active-directory

> they use a call to AcquireTokenByAuthorizationCodeAsync in order to save the token in the cache, so that in other places, the code can just do a AcquireTokenSilentAsync

> The issue comes in when the user is already logged in. The method stored at OpenIdConnectEvents.OnAuthorizationCodeReceived never gets called, since there is no authorization being received. That method only gets called when there's a fresh login.

Also note that "AdalSilentTokenAcquisitionException: Failed to acquire token silently. Call method AcquireToken"  hides the actual response. You need to use Fiddler (or similar) to view the actual error, which can be different. 
E.g I had "The user or administrator has not consented to use the application with ID 'xxx'. Send an interactive authorization request for this user and resource."

**Comment by m-venkat** [comment]
I'm also facing this same error, tried several hours without any solution. I appreciate any help to resolve this issue.

**Comment by michael-freidgeim-webjet** [comment]
@m-venkat To see actual error use Fiddler or enable logging as described in https://www.schaeflein.net/adal-v3-diagnostic-logging/

**Comment by Franklin89** [comment]
I had the same issue after I update my application to 1.1.0 and VS 2017.

The problem was in the method `OnAuthorizationCodeReceived`.

Had to add the AccessToken and IdToken to the `HandleCodeRedemption`.

Full Code:
```csharp
private async Task OnAuthorizationCodeReceived(AuthorizationCodeReceivedContext context)
        {
            // Acquire a Token for the Graph API and cache it using ADAL.  In the TodoListController, we'll use the cache to acquire a token to the Todo List API
            string userObjectId = (context.Ticket.Principal.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier"))?.Value;
            ClientCredential clientCred = new ClientCredential(ClientId, ClientSecret);
            AuthenticationContext authContext = new AuthenticationContext(Authority, new NaiveSessionCache(userObjectId, context.HttpContext.Session));
            AuthenticationResult authResult = await authContext.AcquireTokenByAuthorizationCodeAsync(
                context.ProtocolMessage.Code, new Uri(context.Properties.Items[OpenIdConnectDefaults.RedirectUriForCodePropertiesKey]), clientCred, GraphResourceId);

            // Notify the OIDC middleware that we already took care of code redemption.
            context.HandleCodeRedemption(authResult.AccessToken, authResult.IdToken);
        }
```

This post helped me figure out what it was: [Check it out](https://github.com/aspnet/Security/issues/1068)

**Comment by kickertw** [comment]
I tried the modification referenced by @Franklin89 and am still receiving the same issue.  Is there any resolution to this yet?

**Comment by karthik25** [comment]
I have the same issue and I am having a tough time figuring out why `OnAuthorizationCodeReceived` is not getting fired. Did anybody find a solution for this?

**Comment by jmprieur** [comment]
This is because ASP/NET Core 2.0 now uses the hybrid flow. you need to set the options.ResponseType need to be "code id_token".
The updated sample to ASP.NET core 2.0 (PR referenced aboce) fixes it, although if I understand correctly it might be possible to do even simpler. I'm going to discuss with @vibronet to decide what to do.
