### ISSUE TITLE
Update for Visual Studio 2015 RC

### ISSUE THREAD

**Issue by jwood803** [Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore#3]
I left an [issue](https://github.com/AzureADSamples/WebApp-OpenIdConnect-AspNet5/issues/1) in a similar repository, but I figured I'd add one here, too.

Is it possible to update this sample from CTP to the current RC? I tried to do this with the mentioned sample and ran into a few issues.

**Comment by jwood803** [comment]
And if all the repositories are connected, this can be closed in favor of a more generic one. :]

**Comment by dstrockis** [comment]
Good to track issues in both repos, thank you.

**Comment by guardrex** [comment]
@dstrockis There is some seemingly strange behavior here:
- Each time I trigger a challenge to AAD, it seems to authenticate and postback ... but it appends another nonce, so that cookie becomes quite large if many challenges are issued from the same view.
- On the postback from AAD, I see `.AspNet.Session` and `_ga` headers, and I see posted form data for `code`, `id_token`, `state`, and `session_state`, but `OnAuthorizationCodeReceived` doesn't seem to fire and I can't get a `Context.User` or `ClaimsPrincipal.Current` after the postback from AAD.

I can't tell if I'm doing something wrong or if things are just broken right now and the sample guidance is wrong. If it's not possible to troubleshoot here, do you know of a more current sample I can follow? All I'm trying to do is a vanilla AAD SSO authentication scenario with beta6/MVC 6.

**Comment by pretzelfisch** [comment]
@GuardRex take a look at https://github.com/r2musings/AzureADTest 
primary i need the  app.UseCookieAuthentication(options => { options.AutomaticAuthentication = true; }); 
  Now I have a user who is authenticated.  I just have a problem because ClaimsPrincipal.Current is not getting set so Authorize(role="") attributes are not working.

**Comment by guardrex** [comment]
@pretzelfisch I tried the options setting, but I still have the same result ... it looks like AAD is posting back correctly (I see form values for `code`, `id_token`, `state`, and `session_state` with hashed values) coming back to the app, but the middleware isn't handling it. The nonce might be broken ... it looks like it's appending a new nonce every AAD postback from the same view (i.e., every time I trigger a new challenge). The user is not authenticated. It doesn't look like `OnAuthorizationCodeReceived` is firing. `ClaimsPrincipal.Current` is not established. There are no exceptions, but nothing is happening. I noted that the project you referenced is dnx451, while I'm working in the Core CLR:

```
dnx-coreclr-win-x64.1.0.0-beta6-12005
Win10 preview build 10130
VS 2015 RC
MVC 6
latest beta 6 (nightly builds) of everything except:
"Microsoft.IdentityModel.Clients.ActiveDirectory": "3.1.203031538-alpha"
```

Perhaps, I should run that sample as is and see if I can get that running and go from there.

If anyone on the MS dev team knows what's going on, please let us know where things stand. I can put up a repo of what I have if anyone (e.g., @dstrockis) would be willing to take a look at it.

**Comment by GuardRex** [comment]
Under `dnx451

**Comment by guardrex** [comment]
With minor modifications under `dnx451`, the project runs and works. When I converted it to `dnxcore50`, the middleware failed to process the post from AAD.

Has anyone been able to get AAD SSO working with `dnxcore50`?

**Comment by guardrex** [comment]
Got the word on this ... The sample project incorrectly lists that this NuGet package will work with the Core CLR runtime. See https://github.com/aspnet/Home/issues/674#issuecomment-112683593

I'll have to incorporate ADAL into my Core CLR project directly from source.

**Comment by jmprieur** [comment]
updated to ASP.NET Core 2.0 and Visual Studio 2017
